name: Deploy minor version to PyPI

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    env:
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN_AUTOMATION }}
      - name: Increment version in setup.py
        run: |
          pip3 install bump2version==1.0.1
          ./scripts/increment-version.sh patch
      - uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
          add: "."
          author_email: rogermilroy@users.noreply.github.com
          branch: dev
          # Determines the way the action fills missing author name and email. Three options are available:
          # - github_actor -> UserName <UserName@users.noreply.github.com>
          # - user_info -> Your Display Name <your-actual@email.com>
          # - github_actions -> github-actions <email associated with the github logo>
          # Default:
          default_author: github_actions
          message: "Update version number in setup.py on merge."
          # The flag used on the pull strategy. Use NO-PULL to avoid the action pulling at all.
          # Default: '--no-rebase'
          pull: "NO-PULL"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: build wheel
        run: |
          pip3 install wheel
          python3 setup.py bdist_wheel
      - name: upload wheel
        run: |
          pip3 install twine
          twine upload dist/*
        continue-on-error: true
