###########
# BUILDER #
###########

FROM --platform=$BUILDPLATFORM tensorflow/tensorflow:latest
RUN echo $BUILDPLATFORM
RUN apt-get update
RUN apt-get install -y gcc libpq-dev
RUN python3 --version
RUN apt-get install -y python3.8-venv python3.8-dev python3.8-tk

ENV DEBIAN_FRONTEND=noninteractive
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC
ARG TZ=Etc/UTC
ENV APP_HOME=/home/app/web
RUN mkdir /home/app
RUN mkdir $APP_HOME
RUN mkdir $APP_HOME/staticfiles && mkdir $APP_HOME/media && mkdir $APP_HOME/logging
WORKDIR $APP_HOME
# create the app user
RUN addgroup --system app && adduser --system app --ingroup app
# create the appropriate directories
RUN apt-get install -y postgresql

COPY requirements.txt ./
RUN python3 --version
RUN python3 -m venv /venv
RUN . /venv/bin/activate && pip3 install -r requirements.txt

# copy project
COPY . $APP_HOME
ENV PATH="$/venv/bin:$PATH"

# run entrypoint.sh
ENTRYPOINT ["/home/app/web/scripts/integration_test.sh"]
