name: Python Package Testing

on:
  pull_request:
    branches: [main, dev]

jobs:
  validate:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo - including submodules
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN_AUTOMATION }}
          submodules: "recursive"
      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3

  test:
    needs: validate
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 12
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
        include:
          - os: ubuntu-latest
            path: ~/.cache/pip
          - os: macos-latest
            path: ~/Library/Caches/pip
          - os: windows-latest
            path: ~\AppData\Local\pip\Cache

    steps:
      - name: Checkout repo - including submodules
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN_AUTOMATION }}
          submodules: "recursive"
      - uses: actions/cache@v2
        with:
          path: ${{ matrix.path }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check for macos and install libomp for Boosting libraries to work
        if: startsWith(matrix.os, 'macOS')
        run: brew install libomp
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python -m unittest discover
